### ISSUE TITLE
k3po.tcpdump.converter is falling over java.lang.NumberFormatException: For input string: "FFFFFFFF"

### ISSUE THREAD

**Issue by akrambek** [k3po/k3po.pcap.converter#1]
Steps to reproduce

To reproduce:

* Check out the project
* mvn clean install
* Save the two attached files bad.pcap and bad.pdml to the root of the checked out directory
* java -jar target/com.kaazing.robot.tcpdump.converter-1.0.0.22-SNAPSHOT-jar-with-dependencies.jar bad.pcap bad.pdml 
* Result is the utility fails with the following exception:

```
Exception in thread "main" java.lang.NumberFormatException: For input string: "FFFFFFFF"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:492)
	at java.lang.Integer.parseInt(Integer.java:527)
	at org.kaazing.robot.tcpconverter.parser.Parser.setFieldProperties(Parser.java:242)
	at org.kaazing.robot.tcpconverter.parser.Parser.parseNextPacketFromPdml(Parser.java:138)
	at org.kaazing.robot.tcpconverter.parser.Parser.getNextPacket(Parser.java:78)
	at org.kaazing.robot.tcpconverter.TcpdumpConverter.convertTcpDumpToRpt(TcpdumpConverter.java:31)
	at org.kaazing.robot.tcpconverter.TcpdumpConverter.main(TcpdumpConverter.java:42)
```
* tshark output
```
tshark -v
TShark (Wireshark) 1.99.1 (v1.99.1-0-g4c229ca from master)

Copyright 1998-2014 Gerald Combs <gerald@wireshark.org> and contributors.
License GPLv2+: GNU GPL version 2 or later <http://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compiled (64-bit) with libpcap, without POSIX capabilities, with libz 1.2.3,
with GLib 2.36.0, with SMI 0.4.8, without c-ares, without ADNS, with Lua 5.2,
with GnuTLS 2.12.19, with Gcrypt 1.5.0, with MIT Kerberos, with GeoIP.

Running on Mac OS X 10.10.2, build 14C109 (Darwin 14.1.0), with locale
en_US.UTF-8, with libpcap version 1.5.3 - Apple version 47, with libz 1.2.5,
with GnuTLS 2.12.19, with Gcrypt 1.5.0.
Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (with SSE4.2)

Built using llvm-gcc 4.2.1 (Based on Apple Inc. build 5658) (LLVM build
2336.9.00).
```

[bad.cap | uploaded via ZenHub](https://files.zenhub.io/54d8f46e56e8c9c658df1018)
[bad.pdml | uploaded via ZenHub](https://files.zenhub.io/54d8f47256e8c9c658df1019)

**Comment by dpwspoon** [comment]
This is fixed
